# encoding: utf-8
"""
@author: anna
@contact: a.l.d.latour@liacs.leidenuniv.nl
@time: 5/28/21 2:37 PM
@file: bn2wcnf.py
@desc: Script for generating weighted CNFs from Bayesian networks in .net
format (possibly with evidence in .inst format).
"""

import argparse
import os
import sys
# sys.path.insert(0, os.environ.get('CODE_HOME') + '/bayesiannet2wcnf')     #TODO: use environment vars
# from net2wcnf import Net2UAI2WCNF, CNF2WCNF
from bn2uai2wcnf import Net2UAI2WCNF


parser = argparse.ArgumentParser(description='Convert Bayesian Networks into weighted DIMACS format.')
parser.add_argument_group('Mandatory arguments')
parser.add_argument('--enc', type=int, choices=[2, 5], default=5,
                    help='Specify which encoding to use.')
parser.add_argument('--outdir', type=str, default=None,
                    help='Path to save any files generated by this script.')
parser.add_argument('--net', type=str, help='Specify the path to input Bayesian Network (in .net format).')
parser.add_argument('--evi', type=str, help='Specify the path to the evidence file (in .inst format).')

parser.add_argument_group('Conditional arguments if encoding 5 is chosen')
parser.add_argument('--enc5', type=str, choices=['LOG', 'DIRECT'], default='DIRECT',
                    help='Choose either LOG or DIRECT encoding.')
parser.add_argument('--implicit', action='store_true', default=False,
                    help='Keep the most frequent weight '
                         'implicitly encoded, and compensate with scaling. '
                         'Only applies if --enc == 5. '
                         'WARNING: does not seem to yield correct model counts.')
parser.add_argument('--prime', action='store_true', default=False,
                    help='Simplify CPTs with Quine/McCluskey algorithm. '
                         'Only applies if --enc == 5.')
args = parser.parse_args()

if args.enc == 2:
    bn = Net2ENC2(net_file=args.net, evi_file=args.evi)
    bn.convert2cnf(out_dir=args.outdir + '/acefiles', enc=args.enc)
    bn.convert2wcnf(out_dir=args.outdir + '/wcnf')
elif args.enc == 5:
    bn = Net2UAI2WCNF(net_file=args.net, evi_files=[args.evi])
    bn.save2uai(out_dir=args.outdir)
    bn.convert2cnf(out_dir=args.outdir, enc=args.enc5, implicit=args.implicit, prime=args.prime)
    bn.convert2wcnf(out_dir=args.outdir + '/wcnf')

