#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Short description.

Author:     Anna L.D. Latour
Authors:    [Anna L.D. Latour, And another one, etc]
Contact:    a.l.d.latour@tudelft.nl
Date:       2024-07-06
Maintainer: Anna L.D. Latour
Version:    0.0.1
Credits:    [One developer, And another one, etc]
Copyright:  (C) 2024, Anna L.D. Latour
License:    GPLv3
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; version 3
    of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
    02110-1301, USA.
    
Description: Long description.

"""

from datetime import datetime
import os

from fuzzer_utils import Counter
from report_manager import log_message


def create_directories(cnf_dir: str,
                       bug_dir: str,
                       log_dir: str,
                       generators=None,
                       preprocessors=None,
                       delta_debuggers=None,
                       verbosity=1):
    """ Creates the directories for storing generated problem instances.

    Specifically, in subdirectories cnf_dir and bug_dir, it creates the
    following file tree. Note that preprocessor subdirectories are only created
    if there are preprocessors specified. Similarly, delta-debugger directories
    are only created if delta-debuggers are specified:

    sub_dir
        |-- base
            |-- generator 1
            |-- generator 2
            ...
        |-- preprocessed
            |-- generator 1-preprocessor 1
            |-- generator 1-preprocessor 2
            |-- generator 2-preprocessor 1
            |-- generator 2-preprocessor 2
            ...
        |-- minimised
            |-- generator 1-delta-debugger 1
            |-- generator 1-delta-debugger 2
            |-- generator 1-preprocessor 1-delta-debugger 1
            |-- generator 1-preprocessor 1-delta-debugger 2
            |-- generator 1-preprocessor 2-delta-debugger 1
            |-- generator 1-preprocessor 2-delta-debugger 2
            ...

    :param log_dir:
    :param verbosity:
    :param cnf_dir:         string with path to directory to store instances
    :param bug_dir:         string with path to directory to store buggy instances
    :param generators:      dict with instance generator configuration
    :param preprocessors:   dict with preprocessor configuration
    :param delta_debuggers: dict with delta-debugger configuration
    :return:
    """
    assert generators, "Aborting, must specify a generator config file."

    # Generate all directories for storing CNFs:
    if not os.path.isdir(cnf_dir):
        log_message(f"Creating directory to store generated test instances: {cnf_dir}.")
        os.makedirs(f"{cnf_dir}", exist_ok=True)
    if not os.path.isdir(bug_dir):
        log_message(f"Creating directory to store instances that seem to trigger bugs: {bug_dir}.")
        os.makedirs(f"{bug_dir}", exist_ok=True)
    if not os.path.isdir(log_dir):
        log_message(f"Creating directory to store instances that seem to trigger bugs: {log_dir}.")
        os.makedirs(f"{log_dir}", exist_ok=True)

    for sub_dir in [cnf_dir, bug_dir]:
        for generator in generators:
            generator_dir = f"{cnf_dir}/base/{generator.name}"
            if not os.path.isdir(generator_dir):
                os.makedirs(generator_dir, exist_ok=True)
            if verbosity >= 3:
                log_message(f"Storing problem instances generated by {generator.name} in {generator_dir}.")
    #         if preprocessors is not None:
    #             for preprocessor in preprocessors:
    #                 preprocessor_dir = f"{instance_dir}/preprocessed/{generator.name}-{preprocessor.name}"
    #                 if not os.path.isdir(preprocessor_dir):
    #                     os.makedirs(preprocessor_dir, exist_ok=True)
    #                 if verbosity >= 3:
    #                     log_message(f"Storing problem instances generated by {generator.name} "
    #                                 f"and then preprocessed by {preprocessor.name} in: {preprocessor_dir}.")
    #                 if delta_debuggers is not None:
    #                     for delta_debugger in delta_debuggers:
    #                         minimised_dir = f"{instance_dir}/minimised/{generator.name}-{preprocessor.name}-{delta_debugger.name}"
    #                         if not os.path.isdir(minimised_dir):
    #                             os.makedirs(minimised_dir, exist_ok=True)
    #                         if verbosity >= 3:
    #                             log_message(f"Storing problem instances generated by {generator.name}, "
    #                                         f"then preprocessed by {preprocessor.name}, "
    #                                         f"and finally minimised by {delta_debugger.name} in: {minimised_dir}.")
    #         if delta_debuggers is not None:
    #             for delta_debugger in delta_debuggers:
    #                 minimised_dir = f"{instance_dir}/minimised/{generator.name}-{delta_debugger.name}"
    #                 if not os.path.isdir(minimised_dir):
    #                     os.makedirs(minimised_dir, exist_ok=True)
    #                 if verbosity >= 3:
    #                     log_message(f"Storing problem instances generated by {generator.name} "
    #                                 f"and minimised by {delta_debugger.name} in: {minimised_dir}.")
    # if not os.path.isdir("bug"):
    #     log_message(f"Creating directory to store CNFs that trigger possibly buggy behaviour: {this_dir}/bug.")
    #     os.makedirs("bug", exist_ok=True)


def store_counter_output(command: str,
                         counter_output: str,
                         counter: Counter,
                         log_dir: str):
    log_file = f"{log_dir}/{datetime.now().strftime('%Y-%m-%d_%H%M%S')}_{counter.name}_output.log"
    with open(log_file, 'w') as lf:
        lf.write(f"$ {command}\n")
        lf.write(counter_output)
    return log_file


